# Generated by Django 3.2.7 on 2022-12-18 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=300, null=True)),
                ('diagonal', models.CharField(max_length=5)),
                ('width', models.CharField(max_length=5, null=True)),
                ('height', models.CharField(max_length=5, null=True)),
                ('matrix_type', models.CharField(max_length=10, null=True)),
                ('screen_resolution', models.CharField(max_length=20, null=True)),
                ('fps', models.CharField(max_length=10, null=True)),
                ('monitor_class', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
