# Generated by Django 3.2.7 on 2022-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('length_m', models.CharField(max_length=100)),
                ('weigth', models.CharField(max_length=100)),
                ('matrix', models.CharField(max_length=100)),
            ],
        ),
    ]
