# Generated by Django 3.2.7 on 2022-12-18 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pc_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=5000, null=True)),
                ('price', models.CharField(max_length=20)),
                ('video_memory', models.CharField(max_length=15)),
                ('video_memory_type', models.CharField(max_length=15)),
                ('base_frequency', models.CharField(max_length=20)),
                ('max_frequency', models.CharField(max_length=20)),
                ('video_memory_frequency', models.CharField(max_length=20)),
                ('gpu_type', models.CharField(max_length=20)),
                ('taken_slots_num', models.CharField(max_length=20)),
                ('technical_process', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('recommended_computer_power_supply', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='monitoritemmodel',
            name='price',
            field=models.CharField(default='71 990', max_length=20),
            preserve_default=False,
        ),
    ]
