# Generated by Django 3.2.7 on 2023-02-22 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserPCItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ManyToManyField(to='pc_components.PcComponentModel')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pc.userspcmodel')),
            ],
        ),
    ]
