# Generated by Django 3.2.7 on 2022-12-18 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPcModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('createdAt', models.DateField()),
                ('user', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=300, null=True)),
                ('price', models.CharField(max_length=20)),
                ('video_memory', models.CharField(max_length=15)),
                ('video_memory_type', models.CharField(max_length=15)),
                ('base_frequency', models.CharField(max_length=20)),
                ('max_frequency', models.CharField(max_length=20)),
                ('video_memory_frequency', models.CharField(max_length=20)),
                ('gpu_type', models.CharField(max_length=20)),
                ('taken_slots_num', models.CharField(max_length=20)),
                ('technical_process', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('recommended_computer_power_supply', models.CharField(max_length=20, null=True)),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pc.userspcmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserMonitorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=300, null=True)),
                ('price', models.CharField(max_length=20)),
                ('diagonal', models.CharField(max_length=5)),
                ('width', models.CharField(max_length=5, null=True)),
                ('height', models.CharField(max_length=5, null=True)),
                ('matrix_type', models.CharField(max_length=10, null=True)),
                ('screen_resolution', models.CharField(max_length=20, null=True)),
                ('fps', models.CharField(max_length=10, null=True)),
                ('monitor_class', models.CharField(max_length=20)),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pc.userspcmodel')),
            ],
        ),
    ]
