# Generated by Django 3.2.7 on 2022-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermonitormodel',
            name='short_description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='uservideocardmodel',
            name='short_description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
